tracker_type: botsort  # Tracker type: 'botsort' for BotSORT tracker

# BotSORT parameters
track_high_thresh: 0.5  # Detection confidence threshold
track_low_thresh: 0.1   # Low detection threshold
new_track_thresh: 0.6   # Threshold for starting new tracks
track_buffer: 30        # Frames to keep track alive without matching
match_thresh: 0.8       # IOU threshold for matching
fuse_score: True

gmc_method: None        # Global Motion Compensation method

# ReID parameters
proximity_thresh: 0.5   # Threshold for proximity matching
appearance_thresh: 0.25 # Threshold for appearance matching
with_reid: True        # Enable ReID for tracking
model : app/models/yolo11n-cls.pt